/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2c1700",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2f6b73",
        "on-background": "#0f1d25",
        "on-surface-variant": "#40484a",
        "surface": "#f5faff",
        "inverse-surface": "#24323a",
        "background": "#f5faff",
        "on-secondary-fixed": "#0d1e25",
        "secondary-fixed": "#d3e5f0",
        "secondary": "#50616a",
        "on-secondary": "#ffffff",
        "on-surface": "#0f1d25",
        "error-container": "#ffdad6",
        "inverse-primary": "#96d0d9",
        "tertiary-fixed-dim": "#ffb86a",
        "outline": "#70797a",
        "surface-variant": "#d5e5ef",
        "on-primary-fixed": "#001f23",
        "primary": "#0f535a",
        "tertiary-container": "#8f5500",
        "surface-tint": "#2a676f",
        "surface-container": "#e1f0fb",
        "tertiary-fixed": "#ffdcbc",
        "on-primary-fixed-variant": "#064f56",
        "on-secondary-fixed-variant": "#394951",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#96d0d9",
        "on-primary-container": "#aee9f2",
        "error": "#ba1a1a",
        "surface-dim": "#cddce7",
        "surface-container-highest": "#d5e5ef",
        "on-secondary-container": "#566770",
        "primary-fixed": "#b1edf6",
        "on-tertiary-fixed-variant": "#683d00",
        "surface-container-high": "#dbeaf5",
        "surface-container-low": "#e8f5ff",
        "on-tertiary-container": "#ffd8b3",
        "secondary-container": "#d3e5f0",
        "surface-bright": "#f5faff",
        "on-tertiary": "#ffffff",
        "tertiary": "#6d4000",
        "secondary-fixed-dim": "#b7c9d3",
        "inverse-on-surface": "#e4f3fe",
        "outline-variant": "#bfc8c9",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-sm": "0.375rem",
        "space-xl": "1rem",
        "margin-lg": "1.5rem",
        "gutter-md": "0.75rem",
        "space-md": "0.5rem",
        "margin-md": "1rem",
        "space-xs": "0.25rem",
        "gutter-lg": "1rem",
        "margin": "0.75rem",
        "space-lg": "0.75rem",
        "gutter": "0.5rem"
      },
      fontFamily: {
        "headline-lg": ["\"Source Serif 4\""],
        "headline-md": ["\"Source Serif 4\""],
        "title-md": ["\"Public Sans\""],
        "body-sm": ["\"Public Sans\""],
        "data-mono-md": ["\"Public Sans\""],
        "body-md": ["\"Public Sans\""],
        "body-lg": ["\"Public Sans\""],
        "headline-xl": ["\"Source Serif 4\""],
        "headline-sm": ["\"Source Serif 4\""],
        "title-sm": ["\"Public Sans\""],
        "label-md": ["\"Public Sans\""],
        "label-sm": ["\"Public Sans\""],
        "data-mono-lg": ["\"Public Sans\""]
      },
      fontSize: {
        "headline-lg": ["26px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "600" }],
        "title-md": ["15px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "data-mono-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.03em", "fontWeight": "500" }],
        "body-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-lg": ["15px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "600" }],
        "title-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "label-md": ["11px", { "lineHeight": "14px", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "data-mono-lg": ["18px", { "lineHeight": "22px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
