from app import db
from app.models.role import Role, Permission, RolePermission

class PermissionService:
    # Permission matrix from the design
    PERMISSION_MATRIX = {
        'Command': {
            'user:read': 'all',
            'user:create': 'all',
            'user:update': 'own_station',
            'user:delete': 'all',
            'role:read': 'all',
            'role:create': 'none',
            'role:update': 'none',
            'station:read': 'all',
            'station:create': 'none',
            'station:update': 'none',
            'audit:read': 'all',
            'cargo:read': 'all',
            'cargo:create': 'all',
            'cargo:update': 'all',
            'cargo:delete': 'all',
            'custody:scan': 'all',
            'inventory:read': 'all',
            'inventory:receive': 'all',
            'inventory:consume': 'all',
            'inventory:transfer': 'all',
            'inventory:adjust': 'all',
            'stocktake:perform': 'all',
            'asset:read': 'all',
            'asset:create': 'all',
            'asset:update': 'all',
            'asset:assign': 'all',
            'personnel:read': 'all',
            'personnel:create': 'all',
            'personnel:update': 'all',
            'personnel:move': 'all',
            'checkin:perform': 'all',
            'expedition:read': 'all',
            'expedition:create': 'all',
            'expedition:submit': 'all',
            'expedition:approve': 'all',
            'emergency:read': 'all',
            'emergency:raise': 'all',
            'emergency:acknowledge': 'all',
            'emergency:respond': 'all',
            'emergency:resolve': 'all',
            'sos:read': 'all',
            'sos:raise': 'all',
            'sos:acknowledge': 'all',
            'sos:respond': 'all',
            'sos:resolve': 'all',
            'sos:cancel_confirm': 'all',
            'sos:mutual_aid': 'all',
            'muster:report': 'all',
            'muster:manage': 'all',
            'sync:push': 'all',
            'sync:pull': 'all',
        },
        'Expedition Leader': {
            'user:read': 'own_station',
            'user:create': 'own_station',
            'user:update': 'own_station',
            'user:delete': 'none',
            'role:read': 'all',
            'role:create': 'none',
            'role:update': 'none',
            'station:read': 'all',
            'station:create': 'none',
            'station:update': 'none',
            'audit:read': 'own_station',
            'cargo:read': 'own_station',
            'cargo:create': 'own_station',
            'cargo:update': 'own_station',
            'cargo:delete': 'none',
            'custody:scan': 'own_station',
            'inventory:read': 'own_station',
            'inventory:receive': 'own_station',
            'inventory:consume': 'own_station',
            'inventory:transfer': 'own_station',
            'inventory:adjust': 'own_station',
            'stocktake:perform': 'own_station',
            'asset:read': 'own_station',
            'asset:create': 'own_station',
            'asset:update': 'own_station',
            'asset:assign': 'own_station',
            'personnel:read': 'own_station',
            'personnel:create': 'own_station',
            'personnel:update': 'own_station',
            'personnel:move': 'own_station',
            'checkin:perform': 'own_station',
            'expedition:read': 'own',
            'expedition:create': 'own',
            'expedition:submit': 'own',
            'expedition:approve': 'none',
            'emergency:read': 'own_station',
            'emergency:raise': 'own_station',
            'emergency:acknowledge': 'own_station',
            'emergency:respond': 'own_station',
            'emergency:resolve': 'own_station',
            'sos:read': 'own_station',
            'sos:raise': 'own_station',
            'sos:acknowledge': 'own_station',
            'sos:respond': 'own_station',
            'sos:resolve': 'own_station',
            'sos:cancel_confirm': 'own_station',
            'sos:mutual_aid': 'own_station',
            'muster:report': 'own_station',
            'muster:manage': 'own_station',
            'sync:push': 'all',
            'sync:pull': 'all',
        },
        'Station Leader': {
            'user:read': 'own_station',
            'user:create': 'own_station',
            'user:update': 'own_station',
            'user:delete': 'none',
            'role:read': 'all',
            'role:create': 'none',
            'role:update': 'none',
            'station:read': 'own',
            'station:create': 'none',
            'station:update': 'own',
            'audit:read': 'own_station',
            'cargo:read': 'own_station',
            'cargo:create': 'own_station',
            'cargo:update': 'own_station',
            'cargo:delete': 'none',
            'custody:scan': 'own_station',
            'inventory:read': 'own_station',
            'inventory:receive': 'own_station',
            'inventory:consume': 'own_station',
            'inventory:transfer': 'own_station',
            'inventory:adjust': 'own_station',
            'stocktake:perform': 'own_station',
            'asset:read': 'own_station',
            'asset:create': 'own_station',
            'asset:update': 'own_station',
            'asset:assign': 'own_station',
            'personnel:read': 'own_station',
            'personnel:create': 'own_station',
            'personnel:update': 'own_station',
            'personnel:move': 'own_station',
            'checkin:perform': 'own_station',
            'expedition:read': 'own_station',
            'expedition:create': 'own_station',
            'expedition:submit': 'own_station',
            'expedition:approve': 'none',
            'emergency:read': 'own_station',
            'emergency:raise': 'own_station',
            'emergency:acknowledge': 'own_station',
            'emergency:respond': 'own_station',
            'emergency:resolve': 'own_station',
            'sos:read': 'own_station',
            'sos:raise': 'own_station',
            'sos:acknowledge': 'own_station',
            'sos:respond': 'own_station',
            'sos:resolve': 'own_station',
            'sos:cancel_confirm': 'own_station',
            'sos:mutual_aid': 'own_station',
            'muster:report': 'own_station',
            'muster:manage': 'own_station',
            'sync:push': 'all',
            'sync:pull': 'all',
        },
        'Store/Logistics Officer': {
            'user:read': 'own_station',
            'user:create': 'own_station',
            'user:update': 'own_station',
            'user:delete': 'none',
            'role:read': 'all',
            'role:create': 'none',
            'role:update': 'none',
            'station:read': 'own',
            'station:create': 'none',
            'station:update': 'none',
            'audit:read': 'own_station',
            'cargo:read': 'own_station',
            'cargo:create': 'own_station',
            'cargo:update': 'own_station',
            'cargo:delete': 'none',
            'custody:scan': 'own_station',
            'inventory:read': 'own_station',
            'inventory:receive': 'own_station',
            'inventory:consume': 'own_station',
            'inventory:transfer': 'own_station',
            'inventory:adjust': 'own_station',
            'stocktake:perform': 'own_station',
            'asset:read': 'own_station',
            'asset:create': 'own_station',
            'asset:update': 'own_station',
            'asset:assign': 'own_station',
            'personnel:read': 'own_station',
            'personnel:create': 'own_station',
            'personnel:update': 'own_station',
            'personnel:move': 'own_station',
            'checkin:perform': 'own_station',
            'expedition:read': 'own_station',
            'expedition:create': 'none',
            'expedition:submit': 'none',
            'expedition:approve': 'none',
            'emergency:read': 'own_station',
            'emergency:raise': 'own_station',
            'emergency:acknowledge': 'own_station',
            'emergency:respond': 'own_station',
            'emergency:resolve': 'own_station',
            'sos:read': 'own_station',
            'sos:raise': 'own_station',
            'sos:acknowledge': 'none',
            'sos:respond': 'own_station',
            'sos:resolve': 'none',
            'sos:cancel_confirm': 'none',
            'sos:mutual_aid': 'none',
            'muster:report': 'own_station',
            'muster:manage': 'none',
            'sync:push': 'all',
            'sync:pull': 'all',
        },
        'Field Team Member': {
            'user:read': 'own',
            'user:create': 'none',
            'user:update': 'own',
            'user:delete': 'none',
            'role:read': 'all',
            'role:create': 'none',
            'role:update': 'none',
            'station:read': 'own',
            'station:create': 'none',
            'station:update': 'none',
            'audit:read': 'own',
            'cargo:read': 'own',
            'cargo:create': 'none',
            'cargo:update': 'none',
            'cargo:delete': 'none',
            'custody:scan': 'own',
            'inventory:read': 'own',
            'inventory:receive': 'none',
            'inventory:consume': 'own',
            'inventory:transfer': 'none',
            'inventory:adjust': 'none',
            'stocktake:perform': 'none',
            'asset:read': 'own',
            'asset:create': 'none',
            'asset:update': 'none',
            'asset:assign': 'none',
            'personnel:read': 'own',
            'personnel:create': 'none',
            'personnel:update': 'own',
            'personnel:move': 'none',
            'checkin:perform': 'own',
            'expedition:read': 'own',
            'expedition:create': 'none',
            'expedition:submit': 'none',
            'expedition:approve': 'none',
            'emergency:read': 'own',
            'emergency:raise': 'own',
            'emergency:acknowledge': 'none',
            'emergency:respond': 'own',
            'emergency:resolve': 'none',
            'sos:read': 'own_station',
            'sos:raise': 'own_station',
            'sos:acknowledge': 'none',
            'sos:respond': 'own',
            'sos:resolve': 'none',
            'sos:cancel_confirm': 'none',
            'sos:mutual_aid': 'none',
            'muster:report': 'own',
            'muster:manage': 'none',
            'sync:push': 'all',
            'sync:pull': 'all',
        },
        'Medical Officer': {
            'user:read': 'own_station',
            'user:create': 'own_station',
            'user:update': 'own_station',
            'user:delete': 'none',
            'role:read': 'all',
            'role:create': 'none',
            'role:update': 'none',
            'station:read': 'own',
            'station:create': 'none',
            'station:update': 'none',
            'audit:read': 'own_station',
            'cargo:read': 'own_station',
            'cargo:create': 'none',
            'cargo:update': 'none',
            'cargo:delete': 'none',
            'custody:scan': 'own_station',
            'inventory:read': 'own_station',
            'inventory:receive': 'none',
            'inventory:consume': 'own_station',
            'inventory:transfer': 'none',
            'inventory:adjust': 'own_station',
            'stocktake:perform': 'own_station',
            'asset:read': 'own_station',
            'asset:create': 'none',
            'asset:update': 'none',
            'asset:assign': 'none',
            'personnel:read': 'own_station',
            'personnel:create': 'none',
            'personnel:update': 'own_station',
            'personnel:move': 'none',
            'checkin:perform': 'own_station',
            'expedition:read': 'own_station',
            'expedition:create': 'none',
            'expedition:submit': 'none',
            'expedition:approve': 'none',
            'emergency:read': 'own_station',
            'emergency:raise': 'own_station',
            'emergency:acknowledge': 'own_station',
            'emergency:respond': 'own_station',
            'emergency:resolve': 'own_station',
            'sos:read': 'own_station',
            'sos:raise': 'own_station',
            'sos:acknowledge': 'own_station',
            'sos:respond': 'own_station',
            'sos:resolve': 'own_station',
            'sos:cancel_confirm': 'none',
            'sos:mutual_aid': 'own_station',
            'muster:report': 'own_station',
            'muster:manage': 'none',
            'sync:push': 'all',
            'sync:pull': 'all',
        },
        'Admin': {
            'user:read': 'all',
            'user:create': 'all',
            'user:update': 'all',
            'user:delete': 'all',
            'role:read': 'all',
            'role:create': 'all',
            'role:update': 'all',
            'station:read': 'all',
            'station:create': 'all',
            'station:update': 'all',
            'audit:read': 'all',
            'cargo:read': 'all',
            'cargo:create': 'all',
            'cargo:update': 'all',
            'cargo:delete': 'all',
            'custody:scan': 'all',
            'inventory:read': 'all',
            'inventory:receive': 'all',
            'inventory:consume': 'all',
            'inventory:transfer': 'all',
            'inventory:adjust': 'all',
            'stocktake:perform': 'all',
            'asset:read': 'all',
            'asset:create': 'all',
            'asset:update': 'all',
            'asset:assign': 'all',
            'personnel:read': 'all',
            'personnel:create': 'all',
            'personnel:update': 'all',
            'personnel:move': 'all',
            'checkin:perform': 'all',
            'expedition:read': 'all',
            'expedition:create': 'all',
            'expedition:submit': 'all',
            'expedition:approve': 'all',
            'emergency:read': 'all',
            'emergency:raise': 'all',
            'emergency:acknowledge': 'all',
            'emergency:respond': 'all',
            'emergency:resolve': 'all',
            'sos:read': 'all',
            'sos:raise': 'all',
            'sos:acknowledge': 'all',
            'sos:respond': 'all',
            'sos:resolve': 'all',
            'sos:cancel_confirm': 'all',
            'sos:mutual_aid': 'all',
            'muster:report': 'all',
            'muster:manage': 'all',
            'sync:push': 'all',
            'sync:pull': 'all',
        }
    }

    # Entity string aliases used during sync operation mapping
    ALIAS_MAP = {
        'consignment:create': 'cargo:create',
        'consignment:read': 'cargo:read',
        'consignment:update': 'cargo:update',
        'consignment:delete': 'cargo:delete',
        'custody_log:create': 'custody:scan',
        'custody_log:read': 'cargo:read',
        'incident:create': 'sos:raise',
        'incident:read': 'sos:read',
        'incident:update': 'sos:respond',
        'incident:delete': 'sos:resolve',
        'incident_update:create': 'sos:respond',
        'muster_entry:create': 'muster:report',
        'muster_entry:update': 'muster:report',
        'assistance_request:create': 'sos:mutual_aid',
        'assistance_request:update': 'sos:mutual_aid',
        'station_neighbour:read': 'station:read',
    }

    @staticmethod
    def has_permission(user, permission_name, target_station_id=None, target_user_id=None, station_id=None, **kwargs):
        # 1. Map permission aliases if needed
        permission_name = PermissionService.ALIAS_MAP.get(permission_name, permission_name)

        # 2. Extract station identifier from positional or keyword args
        target_station = target_station_id if target_station_id is not None else station_id

        # 3. Extract role string from string object or ORM model instance
        role_name = getattr(user.role, 'name', user.role) if getattr(user, 'role', None) else None
        if not role_name:
            return False

        # 4. Lookup permission scope
        role_permissions = PermissionService.PERMISSION_MATRIX.get(role_name, {})
        scope = role_permissions.get(permission_name, 'none')

        if scope == 'none':
            return False
        if scope == 'all':
            return True
        if scope == 'own' and target_user_id and target_user_id == getattr(user, 'id', None):
            return True
        if scope == 'own_station':
            # Central Command or users without an attached station ID can access across stations
            if getattr(user, 'station_id', None) is None:
                return True
            if target_station is not None:
                return user.station_id == target_station
            return True

        return False

    @staticmethod
    def get_user_permissions(user):
        role_name = getattr(user.role, 'name', user.role) if getattr(user, 'role', None) else None
        if not role_name:
            return []

        role_permissions = PermissionService.PERMISSION_MATRIX.get(role_name, {})
        return [perm for perm, scope in role_permissions.items() if scope != 'none']