import { useState } from 'react';
import { resolveIncident } from '../../sos/sosOperations';

const RESOLUTION_TYPES = [
  'All Personnel Accounted & Safe',
  'Medical Patient Stabilized / Medevac Dispatched',
  'Fire / Structural Hazard Extinguished & Cleared',
  'Power / HVAC Life Support Restored',
  'Field Team Returned to Station',
  'False Alarm Cleared & Verified by Radio',
  'Mutual Aid Operations Concluded',
];

export default function IncidentResolutionModal({ incident, onClose, onResolved }) {
  const [resolutionType, setResolutionType] = useState(RESOLUTION_TYPES[0]);
  const [commanderNotes, setCommanderNotes] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState('');

  const handlePrintSummary = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to generate the printable incident summary.');
      return;
    }

    const raisedAt = incident.raised_at ? new Date(incident.raised_at).toLocaleString() : 'N/A';
    const resolvedAt = new Date().toLocaleString();
    const durationMin = incident.raised_at
      ? Math.round((Date.now() - new Date(incident.raised_at).getTime()) / 60000)
      : 'N/A';

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>DHRUV After-Action Incident Report — ${incident.id.slice(0, 8)}</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; color: #1d2b33; }
            h1 { font-size: 22px; margin-bottom: 4px; text-transform: uppercase; color: #0f4c5c; }
            .subtitle { font-size: 13px; color: #50616a; margin-bottom: 24px; border-bottom: 2px solid #0f4c5c; padding-bottom: 8px; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }
            .card { border: 1px solid #c3ccd0; border-radius: 4px; padding: 12px; background: #f9fbfb; }
            .label { font-size: 11px; text-transform: uppercase; color: #50616a; font-weight: bold; margin-bottom: 4px; }
            .val { font-size: 14px; font-weight: 600; }
            .section { margin-top: 24px; }
            .notes { background: #eef1f2; border-left: 4px solid #2f6b73; padding: 14px; border-radius: 4px; font-size: 14px; line-height: 1.5; }
            .footer { margin-top: 40px; border-top: 1px solid #c3ccd0; padding-top: 16px; font-size: 12px; color: #50616a; display: flex; justify-content: space-between; }
            @media print { body { padding: 0; } }
          </style>
        </head>
        <body>
          <h1>National Centre for Polar and Ocean Research (NCPOR)</h1>
          <div class="subtitle">DHRUV Polar Expedition System — Official Emergency Incident Closure Report</div>

          <div class="grid">
            <div class="card">
              <div class="label">Incident ID</div>
              <div class="val">${incident.id}</div>
            </div>
            <div class="card">
              <div class="label">Emergency Category</div>
              <div class="val">${incident.sos_category || incident.type || 'EMERGENCY'}</div>
            </div>
            <div class="card">
              <div class="label">Station Location</div>
              <div class="val">Station ID: ${incident.station_id || 'Maitri / Bharati'}</div>
            </div>
            <div class="card">
              <div class="label">Severity Level</div>
              <div class="val">${(incident.severity || 'CRITICAL').toUpperCase()} (Escalation: Level ${incident.escalation_level ?? 0})</div>
            </div>
            <div class="card">
              <div class="label">Alert Raised At</div>
              <div class="val">${raisedAt}</div>
            </div>
            <div class="card">
              <div class="label">Incident Resolved At</div>
              <div class="val">${resolvedAt} (Duration: ${durationMin} mins)</div>
            </div>
          </div>

          <div class="section">
            <div class="label">Incident Title & Description</div>
            <div class="notes" style="margin-bottom: 16px;">
              <strong>${incident.title || 'Untitled Incident'}</strong><br/>
              ${incident.description || 'No description recorded.'}
            </div>
          </div>

          <div class="section">
            <div class="label">Resolution Determination & Commander Notes</div>
            <div class="notes">
              <strong>Outcome: ${resolutionType}</strong><br/><br/>
              ${commanderNotes || 'No notes provided.'}
            </div>
          </div>

          <div class="footer">
            <div>Signed off by Polar Station Incident Commander</div>
            <div>Generated by DHRUV Offline Emergency Engine • SIH-2026-26062</div>
          </div>

          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!commanderNotes.trim() || commanderNotes.trim().length < 5) {
      setError('Please provide a mandatory resolution summary (minimum 5 characters).');
      return;
    }

    try {
      setIsSubmitting(true);
      setError('');
      await resolveIncident(incident.id, commanderNotes, resolutionType);
      if (onResolved) onResolved();
      onClose();
    } catch (err) {
      setError(err.message || 'Failed to resolve incident');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-fadeIn">
      <div className="bg-[#EEF1F2] border border-[#C3CCD0] rounded-[4px] shadow-2xl w-full max-w-xl text-[#1D2B33] overflow-hidden">
        {/* Header */}
        <div className="bg-[#E4E8EA] px-5 py-4 border-b border-[#C3CCD0] flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-[#3F6B3A] text-[24px]">task_alt</span>
            <div>
              <h2 className="font-headline-sm text-headline-sm font-bold text-[#1D2B33]">
                Close & Resolve Incident
              </h2>
              <p className="text-xs text-[#50616a]">
                Formal Commander sign-off & after-action record
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-[#50616a] hover:text-[#1D2B33] p-1 rounded transition-colors"
          >
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>

        {/* Content */}
        <form onSubmit={handleSubmit} className="p-5 space-y-4">
          {error && (
            <div className="p-3 bg-red-100 border border-red-300 text-red-800 text-xs rounded font-medium flex items-center gap-2">
              <span className="material-symbols-outlined text-[16px]">error</span>
              <span>{error}</span>
            </div>
          )}

          <div className="p-3 bg-white border border-[#C3CCD0] rounded text-xs space-y-1">
            <div className="flex justify-between text-[#50616a]">
              <span>Target Incident:</span>
              <span className="font-mono">{incident.id.slice(0, 13)}...</span>
            </div>
            <div className="font-semibold text-sm text-[#1D2B33]">
              {incident.title || 'SOS Alert'}
            </div>
            <div className="text-[#50616a]">
              Category: <span className="font-medium text-[#1D2B33]">{incident.sos_category || incident.type || 'N/A'}</span> • Severity: <span className="font-medium text-[#C2410C] uppercase">{incident.severity}</span>
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-[#50616a] mb-1">
              Resolution Outcome
            </label>
            <select
              value={resolutionType}
              onChange={(e) => setResolutionType(e.target.value)}
              className="w-full h-9 px-3 bg-white border border-[#C3CCD0] rounded text-sm text-[#1D2B33] focus:outline-none focus:border-primary"
            >
              {RESOLUTION_TYPES.map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-[#50616a] mb-1">
              Commander Resolution Notes <span className="text-red-500">* (Mandatory)</span>
            </label>
            <textarea
              rows={4}
              required
              value={commanderNotes}
              onChange={(e) => setCommanderNotes(e.target.value)}
              placeholder="Detail the response actions taken, current status of involved personnel, medical condition, equipment repairs, and follow-up directives..."
              className="w-full p-3 bg-white border border-[#C3CCD0] rounded text-sm text-[#1D2B33] placeholder-[#50616a]/60 focus:outline-none focus:border-primary"
            />
            <p className="text-[11px] text-[#50616a] mt-1">
              This record is immutably committed to Dexie and the polar expedition audit trail.
            </p>
          </div>

          {/* Footer Actions */}
          <div className="pt-3 border-t border-[#C3CCD0] flex items-center justify-between gap-3">
            <button
              type="button"
              onClick={handlePrintSummary}
              className="h-9 px-3 bg-white border border-[#C3CCD0] text-[#1D2B33] text-xs font-semibold rounded hover:bg-gray-50 flex items-center gap-1.5 transition-colors"
            >
              <span className="material-symbols-outlined text-[16px]">print</span>
              <span>Print After-Action Report</span>
            </button>

            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="h-9 px-4 bg-transparent border border-[#C3CCD0] text-[#50616a] text-xs font-semibold rounded hover:bg-gray-100"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="h-9 px-4 bg-[#3F6B3A] hover:bg-[#33562E] text-white text-xs font-bold rounded shadow flex items-center gap-1.5 transition-colors disabled:opacity-50"
              >
                <span className="material-symbols-outlined text-[16px]">check_circle</span>
                <span>{isSubmitting ? 'Resolving...' : 'Confirm Resolution'}</span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
