"""add custody log table

Revision ID: 435f52202539
Revises: f86ce5d8d692
Create Date: 2026-10-01 09:45:55.960291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '435f52202539'
down_revision = 'f86ce5d8d692'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custody_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consignment_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('signature_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('maintenance_records')
    op.drop_table('custody_scans')
    op.drop_table('incidents')
    op.drop_table('assets')
    op.drop_table('stock_movements')
    op.drop_table('incident_updates')
    op.drop_table('check_ins')
    op.drop_table('inventory_items')
    op.drop_table('consignment_items')
    op.drop_table('personnel')
    op.drop_index(op.f('idx_audit_log_entity'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_user'), table_name='audit_log')
    op.drop_index(op.f('idx_stations_region'), table_name='stations')
    op.alter_column('sync_cursors', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_station'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_station'), 'users', ['station_id'], unique=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role_id'], unique=False)
    op.alter_column('sync_cursors', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('idx_stations_region'), 'stations', ['region'], unique=False)
    op.create_index(op.f('idx_audit_log_user'), 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_log_timestamp'), 'audit_log', ['server_timestamp'], unique=False)
    op.create_index(op.f('idx_audit_log_entity'), 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('personnel',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('personnel_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('personnel_pkey'))
    )
    op.create_table('consignment_items',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('consignment_items_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consignment_items_pkey'))
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('inventory_items_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_items_pkey'))
    )
    op.create_table('check_ins',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('check_ins_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('check_ins_pkey'))
    )
    op.create_table('incident_updates',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('incident_updates_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incident_updates_pkey'))
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('stock_movements_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_movements_pkey'))
    )
    op.create_table('assets',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('assets_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey'))
    )
    op.create_table('incidents',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('incidents_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_table('custody_scans',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('custody_scans_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('custody_scans_pkey'))
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('maintenance_records_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_records_pkey'))
    )
    op.drop_table('custody_logs')
    # ### end Alembic commands ###
