"""add user_id to sync_receipts

Revision ID: bff9e2563baf
Revises: foundation_schema
Create Date: 2026-10-01 23:56:37.395224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bff9e2563baf'
down_revision = 'foundation_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custody_logs')
    op.drop_constraint(op.f('alerts_dedupe_key_key'), 'alerts', type_='unique')
    op.create_index(op.f('ix_alerts_created_by'), 'alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_alerts_dedupe_key'), 'alerts', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_station_id'), 'alerts', ['station_id'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.drop_constraint(op.f('assets_asset_number_key'), 'assets', type_='unique')
    op.create_index(op.f('ix_assets_asset_number'), 'assets', ['asset_number'], unique=True)
    op.create_index(op.f('ix_assets_assigned_to_user_id'), 'assets', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_assets_category'), 'assets', ['category'], unique=False)
    op.create_index(op.f('ix_assets_created_by'), 'assets', ['created_by'], unique=False)
    op.create_index(op.f('ix_assets_station_id'), 'assets', ['station_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.alter_column('change_log', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('change_log', 'serialized_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_change_log_entity'), table_name='change_log')
    op.drop_index(op.f('ix_change_log_station_id'), table_name='change_log')
    op.create_index(op.f('ix_check_ins_created_by'), 'check_ins', ['created_by'], unique=False)
    op.create_index(op.f('ix_check_ins_personnel_id'), 'check_ins', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_check_ins_station_id'), 'check_ins', ['station_id'], unique=False)
    op.create_index(op.f('ix_check_ins_status'), 'check_ins', ['status'], unique=False)
    op.create_index(op.f('ix_consignment_items_consignment_id'), 'consignment_items', ['consignment_id'], unique=False)
    op.create_index(op.f('ix_consignment_items_created_by'), 'consignment_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_consignment_items_inventory_item_id'), 'consignment_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_consignment_items_station_id'), 'consignment_items', ['station_id'], unique=False)
    op.create_foreign_key(None, 'consignment_items', 'inventory_items', ['inventory_item_id'], ['id'])
    op.alter_column('consignments', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('consignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('consignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('uq_consignments_number'), table_name='consignments', postgresql_where='(consignment_number IS NOT NULL)')
    op.create_index(op.f('ix_consignments_consignment_number'), 'consignments', ['consignment_number'], unique=True)
    op.create_index(op.f('ix_consignments_created_by'), 'consignments', ['created_by'], unique=False)
    op.create_index(op.f('ix_consignments_destination_station_id'), 'consignments', ['destination_station_id'], unique=False)
    op.create_index(op.f('ix_consignments_origin_station_id'), 'consignments', ['origin_station_id'], unique=False)
    op.create_index(op.f('ix_consignments_priority'), 'consignments', ['priority'], unique=False)
    op.create_index(op.f('ix_consignments_tracking_number'), 'consignments', ['tracking_number'], unique=False)
    op.create_foreign_key(None, 'consignments', 'users', ['created_by'], ['id'])
    op.create_index(op.f('ix_custody_scans_consignment_id'), 'custody_scans', ['consignment_id'], unique=False)
    op.create_index(op.f('ix_custody_scans_created_by'), 'custody_scans', ['created_by'], unique=False)
    op.create_index(op.f('ix_custody_scans_scan_type'), 'custody_scans', ['scan_type'], unique=False)
    op.create_index(op.f('ix_custody_scans_scanned_by'), 'custody_scans', ['scanned_by'], unique=False)
    op.create_index(op.f('ix_custody_scans_station_id'), 'custody_scans', ['station_id'], unique=False)
    op.create_index(op.f('ix_incident_updates_created_by'), 'incident_updates', ['created_by'], unique=False)
    op.create_index(op.f('ix_incident_updates_incident_id'), 'incident_updates', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_updates_station_id'), 'incident_updates', ['station_id'], unique=False)
    op.create_index(op.f('ix_incident_updates_user_id'), 'incident_updates', ['user_id'], unique=False)
    op.create_index(op.f('ix_incidents_created_by'), 'incidents', ['created_by'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_station_id'), 'incidents', ['station_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_type'), 'incidents', ['type'], unique=False)
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_items_created_by'), 'inventory_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_inventory_items_station_id'), 'inventory_items', ['station_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_asset_id'), 'maintenance_records', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_created_by'), 'maintenance_records', ['created_by'], unique=False)
    op.create_index(op.f('ix_maintenance_records_performed_by'), 'maintenance_records', ['performed_by'], unique=False)
    op.create_index(op.f('ix_maintenance_records_station_id'), 'maintenance_records', ['station_id'], unique=False)
    op.create_index(op.f('ix_personnel_created_by'), 'personnel', ['created_by'], unique=False)
    op.create_index(op.f('ix_personnel_current_station_id'), 'personnel', ['current_station_id'], unique=False)
    op.create_index(op.f('ix_personnel_station_id'), 'personnel', ['station_id'], unique=False)
    op.create_index(op.f('ix_personnel_status'), 'personnel', ['status'], unique=False)
    op.create_index(op.f('ix_personnel_user_id'), 'personnel', ['user_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_by'), 'stock_movements', ['created_by'], unique=False)
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_station_id'), 'stock_movements', ['station_id'], unique=False)
    op.add_column('sync_receipts', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_sync_receipts_user_id'), 'sync_receipts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'sync_receipts', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sync_receipts', type_='foreignkey')
    op.drop_index(op.f('ix_sync_receipts_user_id'), table_name='sync_receipts')
    op.drop_column('sync_receipts', 'user_id')
    op.drop_index(op.f('ix_stock_movements_station_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_by'), table_name='stock_movements')
    op.drop_index(op.f('ix_personnel_user_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_status'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_station_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_current_station_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_created_by'), table_name='personnel')
    op.drop_index(op.f('ix_maintenance_records_station_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_performed_by'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_created_by'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_asset_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_inventory_items_station_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_created_by'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_index(op.f('ix_incidents_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_station_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_by'), table_name='incidents')
    op.drop_index(op.f('ix_incident_updates_user_id'), table_name='incident_updates')
    op.drop_index(op.f('ix_incident_updates_station_id'), table_name='incident_updates')
    op.drop_index(op.f('ix_incident_updates_incident_id'), table_name='incident_updates')
    op.drop_index(op.f('ix_incident_updates_created_by'), table_name='incident_updates')
    op.drop_index(op.f('ix_custody_scans_station_id'), table_name='custody_scans')
    op.drop_index(op.f('ix_custody_scans_scanned_by'), table_name='custody_scans')
    op.drop_index(op.f('ix_custody_scans_scan_type'), table_name='custody_scans')
    op.drop_index(op.f('ix_custody_scans_created_by'), table_name='custody_scans')
    op.drop_index(op.f('ix_custody_scans_consignment_id'), table_name='custody_scans')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'consignments', type_='foreignkey')
    op.drop_index(op.f('ix_consignments_tracking_number'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_priority'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_origin_station_id'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_destination_station_id'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_created_by'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_consignment_number'), table_name='consignments')
    op.create_index(op.f('uq_consignments_number'), 'consignments', ['consignment_number'], unique=True, postgresql_where='(consignment_number IS NOT NULL)')
    op.alter_column('consignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('consignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('consignments', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'consignment_items', type_='foreignkey')
    op.drop_index(op.f('ix_consignment_items_station_id'), table_name='consignment_items')
    op.drop_index(op.f('ix_consignment_items_inventory_item_id'), table_name='consignment_items')
    op.drop_index(op.f('ix_consignment_items_created_by'), table_name='consignment_items')
    op.drop_index(op.f('ix_consignment_items_consignment_id'), table_name='consignment_items')
    op.drop_index(op.f('ix_check_ins_status'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_station_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_personnel_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_created_by'), table_name='check_ins')
    op.create_index(op.f('ix_change_log_station_id'), 'change_log', ['station_id'], unique=False)
    op.create_index(op.f('ix_change_log_entity'), 'change_log', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('change_log', 'serialized_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('change_log', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_station_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_by'), table_name='assets')
    op.drop_index(op.f('ix_assets_category'), table_name='assets')
    op.drop_index(op.f('ix_assets_assigned_to_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_number'), table_name='assets')
    op.create_unique_constraint(op.f('assets_asset_number_key'), 'assets', ['asset_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_station_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedupe_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_by'), table_name='alerts')
    op.create_unique_constraint(op.f('alerts_dedupe_key_key'), 'alerts', ['dedupe_key'], postgresql_nulls_not_distinct=False)
    op.create_table('custody_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('consignment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('signature_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], name=op.f('custody_logs_consignment_id_fkey')),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('custody_logs_performed_by_fkey')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('custody_logs_station_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('custody_logs_pkey'))
    )
    # ### end Alembic commands ###
